// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onMesajChange();
void onLedChange();
void onOrarChange();
void onAfiseazaMesajChange();

String mesaj;
CloudLight led;
CloudTemperatureSensor temperature;
CloudSchedule orar;
bool afiseazaMesaj;

void initProperties(){

  ArduinoCloud.addProperty(mesaj, READWRITE, ON_CHANGE, onMesajChange);
  ArduinoCloud.addProperty(led, READWRITE, ON_CHANGE, onLedChange);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(orar, READWRITE, ON_CHANGE, onOrarChange);
  ArduinoCloud.addProperty(afiseazaMesaj, READWRITE, ON_CHANGE, onAfiseazaMesajChange);



}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
